name: PostgreSQL service example
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  container-job:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 16 ]

    name: Node ${{ matrix.node }} sample

    services:

      postgres:

        image: postgres:13-alpine

        env:
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: team3
          POSTGRES_DB: goodcar
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
        ports:
          - 5432:5432

    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run:  npm run test

        env: 
          DB_URL_TEST: postgres://team3:12345@localhost:5432/goodcar
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          userToken: ${{secrets.userToken}}
